### ISSUE TITLE
Error in forward method of ResPath?

### ISSUE THREAD

**Issue by dlorenz70** [Latterlig96/DCUnet#1]
In the init method of class ResPath, the ModuleList module is filled with 2*self.length elements but in the forward method only the first half is called:
```
for i in range(self.length-1):
            shortcut = out
            shortcut = self.module[i](shortcut)
            out = self.module[i+1](out)
            out = torch.add(shortcut, out)
            out = F.relu(out)
            out = self.bn(out)
```

I believe that it should be:
```
for i in range(self.length-1):
            shortcut = out
            shortcut = self.module[i*2](shortcut)
            out = self.module[i*2+1](out)
            out = torch.add(shortcut, out)
            out = F.relu(out)
            out = self.bn(out)
```

**Comment by Latterlig96** [comment]
Thank you for your issue, I applied your suggestion to code already and it worked as expected. I must have overlooked this small bug and because I do not have much time I stopped developing this repo.
